from reportlab.platypus import (
    SimpleDocTemplate,
    Spacer,
    Paragraph
)

from reportlab.lib import colors
from reportlab.lib.styles import (
    getSampleStyleSheet
)


def generate_pdf_report(
    total_revenue,
    total_units,
    stock_left,
    avg_price,
    predicted_sales,
    top_revenue_med,
    best_category,
    best_month
):

    file_path = (
        "varg_medi_report.pdf"
    )

    doc = SimpleDocTemplate(
        file_path
    )

    styles = (
        getSampleStyleSheet()
    )

    content = []

    title = Paragraph(
        "Varg-Medi Analytics Report",
        styles["Title"]
    )

    content.append(title)

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Business Summary",
            styles["Heading2"]
        )
    )

    report_data = [
        f"Total Revenue: ₹{total_revenue:,}",
        f"Units Sold: {total_units}",
        f"Stock Left: {stock_left}",
        f"Average Price: ₹{avg_price}",
        f"Predicted Next Month Sales: {predicted_sales}",
        f"Highest Revenue Medicine: {top_revenue_med}",
        f"Best Category: {best_category}",
        f"Best Sales Month: {best_month}"
    ]

    for item in report_data:
        content.append(
            Paragraph(
                item,
                styles["BodyText"]
            )
        )

    content.append(
        Spacer(1, 20)
    )

    footer = Paragraph(
        "Generated by Varg-Medi Analytics",
        styles["Italic"]
    )

    content.append(
        footer
    )

    doc.build(content)

    return file_path